name: owl_openapi_petstore
version: 0.0.1
publish_to: none

dependencies:
  meta: ^1.0.0
  json_annotation: ^3.0.0
  shelf: '>=0.5.6 <0.8.0'
  shelf_router: ^0.7.0

dev_dependencies:
  build_runner: '^1.0.0'
  build_verify: ^1.1.1
  json_serializable: '^3.0.0'
  shelf_router_generator: ^0.7.0
  test: '^1.3.0'
