name: owl_http
description: >
    Source code generator for OpenAPI v3 REST server and client.
version: 0.1.0
author: Istvan Soos <istvan.soos@agilord.com>

homepage: https://github.com/agilord/owl

environment:
  sdk: '>=2.4.0 <3.0.0'

dependencies:
  json_annotation: ^3.0.0
  meta: ^1.0.0
  open_api: ^2.0.1
  path: ^1.0.0
  yaml: ^2.1.0

dev_dependencies:
  build_runner: '^1.0.0'
  build_verify: ^1.1.1
  json_serializable: '^3.0.0'
  pedantic: ^1.0.0
  test: ^1.0.0
