name: owl_example
description: >
    Owl code generator examples.
    It supports JSON serialization, HTTP APIs and SQL CRUD.
version: 0.4.0
author: Istvan Soos <istvan.soos@agilord.com>

homepage: https://github.com/agilord/owl

environment:
  sdk: '>=2.0.0 <3.0.0'

dependencies:
  owl: ^0.4.0

dev_dependencies:
  owl_codegen: ^0.4.0
  test: '^1.3.0'

dependency_overrides:
  owl:
    path: '../owl'
  owl_codegen:
    path: '../owl_codegen'
