name: owl_example
description: >
    Owl code generator examples.
    It supports JSON serialization, HTTP APIs and SQL CRUD.
version: 0.1.0
author: Istvan Soos <istvan.soos@agilord.com>

homepage: https://github.com/agilord/owl

environment:
  sdk: '>=1.0.0 <2.0.0'

dependencies:
  owl: '0.1.0'
  postgresql: 'any'

dev_dependencies:
  owl_codegen: '0.1.0'
  test: '>=0.12.0 <0.13.0'

dependency_overrides:
  owl:
    path: '../owl'
  owl_codegen:
    path: '../owl_codegen'
