name: owl_sql
description: >
    Source code generator for SQL CRUD (Postgresql).
version: 0.6.0
author: Istvan Soos <istvan.soos@agilord.com>

homepage: https://github.com/agilord/owl

environment:
  sdk: '>=2.0.0 <3.0.0'

dev_dependencies:
  postgres: ^1.0.0
  page: ^1.0.0
  test: ^1.0.0
