name: owl_sql
description: >
    Source code generator for SQL CRUD (Postgresql and CockroachDB-flavoured SQL).
version: 0.12.0

homepage: https://github.com/agilord/owl

environment:
  sdk: '^3.0.0'

dev_dependencies:
  page: ^1.2.0
  lints: ^3.0.0
  postgres: ^3.0.0
  test: ^1.0.0
