name: owl_sql
description: >
    Source code generator for SQL CRUD (Postgresql and CockroachDB-flavoured SQL).
version: 0.13.0

homepage: https://github.com/agilord/owl

environment:
  sdk: '^3.0.0'

dependencies:
  collection: ^1.18.0
  page: ^1.2.0
  postgres: ^3.2.0

dev_dependencies:
  docker_process: ^1.3.1
  meta: ^1.14.0
  path: ^1.9.0
  lints: ^3.0.0
  test: ^1.0.0
