name: owl_sql
description: >
    Source code generator for SQL CRUD (Postgresql and CockroachDB-flavoured SQL).
version: 0.10.0

homepage: https://github.com/agilord/owl

environment:
  sdk: '>=2.12.0 <3.0.0'

dev_dependencies:
  page: ^1.2.0
  pedantic: ^1.0.0
  postgres: ^2.0.0
  test: ^1.0.0
