name: owl_codegen
description: >
    Source code generator for JSON serialization, HTTP APIs and SQL CRUD.
version: 0.4.0+1
author: Istvan Soos <istvan.soos@agilord.com>

homepage: https://github.com/agilord/owl

environment:
  sdk: '>=2.0.0 <3.0.0'

dependencies:
  owl: ^0.4.0
    # path: '../owl'
  analyzer: ^0.32.3
  args: ^1.3.0
  build: ^0.12.0
  build_runner: ^0.9.1
  quiver: ^0.29.0
  source_gen: ^0.8.3
  yaml: ^2.1.12
