name: owl_codegen
description: >
    Source code generator for JSON serialization, HTTP APIs and SQL CRUD.
version: 0.2.2
author: Istvan Soos <istvan.soos@agilord.com>

homepage: https://github.com/agilord/owl

environment:
  sdk: '>=1.20.0 <2.0.0'

dependencies:
  owl: ^0.2.1
    # path: '../owl'
  analyzer: ^0.29.10
  args: ^0.13.7
  build: ^0.10.0
  build_runner: ^0.4.0
  id: ^1.0.1
  source_gen: ^0.7.0
  yaml: ^2.1.12

dev_dependencies:
  test: '>=0.12.0 <0.13.0'
